<a href="https://colab.research.google.com/github/CodeHunterOfficial/DL_20241S/blob/main/Lecture_7_Transformer_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [94]:
import numpy as np

WK1 = np.array(
    [[1, 0, 1], [0, 1, 0],
     [1, 0, 1], [0, 1, 0]])
WV1 = np.array(
    [[0, 1, 1], [1, 0, 0],
     [1, 0, 1], [0, 1, 0]])
WQ1 = np.array(
    [[0, 0, 0], [1, 1, 0],
     [0, 0, 1], [1, 0, 0]])

WK2 = np.array(
    [[0, 1, 1], [1, 0, 1],
     [1, 1, 0], [0, 1, 0]])
WV2 = np.array(
    [[1, 0, 0], [0, 1, 1],
     [0, 0, 1], [1, 0, 0]])
WQ2 = np.array(
    [[1, 0, 1], [0, 1, 0],
     [1, 0, 0], [0, 1, 1]])

In [95]:
embedding = np.array([[1, 3, 3, 5], [2.84, 3.99, 4, 6]])
K1 = embedding @ WK1
#K1 = np.dot(embedding, WK1)
print(K1)

[[4.   8.   4.  ]
 [6.84 9.99 6.84]]


In [96]:
V1 = embedding @ WV1
print(V1)

[[6.   6.   4.  ]
 [7.99 8.84 6.84]]


In [97]:
Q1 = embedding @ WQ1
print(Q1)

[[8.   3.   3.  ]
 [9.99 3.99 4.  ]]


In [98]:
scores1 = Q1 @ K1.T
print(scores1)

[[ 68.     105.21  ]
 [ 87.88   135.5517]]


In [99]:
scores1 = scores1 / np.sqrt(3)
print(scores1)

[[39.2598183  60.74302182]
 [50.73754166 78.26081048]]


In [100]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=1, keepdims=True)

scores1 = softmax(scores1)
print(scores1)

[[4.67695573e-10 1.00000000e+00]
 [1.11377182e-12 1.00000000e+00]]


In [101]:
attention1 = scores1 @ V1
print(attention1)

[[7.99 8.84 6.84]
 [7.99 8.84 6.84]]


In [102]:
def attention(x, WQ, WK, WV):
    K = x @ WK
    V = x @ WV
    Q = x @ WQ

    scores = Q @ K.T
    scores = scores / np.sqrt(3)
    scores = softmax(scores)
    scores = scores @ V
    return scores

attention1=attention(embedding, WQ1, WK1, WV1)
print(attention1)

[[7.99 8.84 6.84]
 [7.99 8.84 6.84]]


In [103]:
attention2 = attention(embedding, WQ2, WK2, WV2)
print(attention2)

[[8.84 3.99 7.99]
 [8.84 3.99 7.99]]


In [104]:
soft=softmax(((embedding @ WQ2) @ (embedding @ WK2).T) / np.sqrt(3))
print(soft)

[[1.10613872e-14 1.00000000e+00]
 [4.95934510e-20 1.00000000e+00]]


In [105]:
def attention(x, WQ, WK, WV):
    K = x @ WK
    V = x @ WV
    Q = x @ WQ

    scores = Q @ K.T
    scores = scores / 30  # we just changed this
    scores = softmax(scores)
    scores = scores @ V
    return scores

attention1 = attention(embedding, WQ1, WK1, WV1)
print(attention1)

[[7.54348784 8.20276657 6.20276657]
 [7.65266185 8.35857269 6.35857269]]


In [106]:
attention2 = attention(embedding, WQ2, WK2, WV2)
print(attention2)

[[8.45589591 3.85610456 7.72085664]
 [8.63740591 3.91937741 7.84804146]]


In [107]:
attentions = np.concatenate([attention1, attention2], axis=1)
print(attentions)

[[7.54348784 8.20276657 6.20276657 8.45589591 3.85610456 7.72085664]
 [7.65266185 8.35857269 6.35857269 8.63740591 3.91937741 7.84804146]]


In [108]:
# Просто произвольные значения
W = np.array(
    [
        [0.79445237, 0.1081456, 0.27411536, 0.78394531],
        [0.29081936, -0.36187258, -0.32312791, -0.48530339],
        [-0.36702934, -0.76471963, -0.88058366, -1.73713022],
        [-0.02305587, -0.64315981, -0.68306653, -1.25393866],
        [0.29077448, -0.04121674, 0.01509932, 0.13149906],
        [0.57451867, -0.08895355, 0.02190485, 0.24535932],
    ]
)
Z = attentions @ W
print(Z)

[[ 11.46394285 -13.18016471 -11.59340253 -17.04387829]
 [ 11.62608573 -13.47454936 -11.87126395 -17.4926367 ]]


In [109]:
W1 = np.random.randn(4, 8)
W2 = np.random.randn(8, 4)
b1 = np.random.randn(8)
b2 = np.random.randn(4)

In [110]:
def relu(x):
    return np.maximum(0, x)

def feed_forward(Z, W1, b1, W2, b2):
    return relu(Z.dot(W1) + b1).dot(W2) + b2

output_encoder = feed_forward(Z, W1, b1, W2, b2)
print(output_encoder)

[[-40.81218994 102.60294212 -24.68209298  46.53786689]
 [-41.22808664 104.77918506 -25.20966077  46.96370499]]


In [111]:
import numpy as np

# Указываем размерности
d_embedding = 4
d_key = d_value = d_query = 3
d_feed_forward = 8
n_attention_heads = 2

# Функция для выполнения attention механизма
def attention(x, WQ, WK, WV):
    K = x @ WK  # Умножение входа на матрицу ключей
    V = x @ WV  # Умножение входа на матрицу значений
    Q = x @ WQ  # Умножение входа на матрицу запросов

    scores = Q @ K.T  # Вычисление попарных скалярных произведений между запросами и ключами
    scores = scores / np.sqrt(d_key)  # Нормирование на корень из размерности ключа
    scores = softmax(scores)  # Применение softmax для получения весов
    scores = scores @ V  # Взвешенная сумма значений с учетом полученных весов
    return scores

# Функция для выполнения механизма multi-head attention
def multi_head_attention(x, WQs, WKs, WVs):
    attentions = np.concatenate(
        [attention(x, WQ, WK, WV) for WQ, WK, WV in zip(WQs, WKs, WVs)], axis=1
    )
    W = np.random.randn(n_attention_heads * d_value, d_embedding)
    return attentions @ W

# Функция для выполнения feed-forward сети
def feed_forward(Z, W1, b1, W2, b2):
    return relu(Z.dot(W1) + b1).dot(W2) + b2

# Функция для выполнения блока кодировщика
def encoder_block(x, WQs, WKs, WVs, W1, b1, W2, b2):
    Z = multi_head_attention(x, WQs, WKs, WVs)  # Применение multi-head attention
    Z = feed_forward(Z, W1, b1, W2, b2)  # Применение feed-forward сети
    return Z

# Функция для создания случайного блока кодировщика
def random_encoder_block(x):
    # Генерация случайных матриц для запросов, ключей и значений
    WQs = [
        np.random.randn(d_embedding, d_query) for _ in range(n_attention_heads)
    ]
    WKs = [
        np.random.randn(d_embedding, d_key) for _ in range(n_attention_heads)
    ]
    WVs = [
        np.random.randn(d_embedding, d_value) for _ in range(n_attention_heads)
    ]
    # Генерация случайных матриц и векторов для feed-forward сети
    W1 = np.random.randn(d_embedding, d_feed_forward)
    b1 = np.random.randn(d_feed_forward)
    W2 = np.random.randn(d_feed_forward, d_embedding)
    b2 = np.random.randn(d_embedding)
    return encoder_block(x, WQs, WKs, WVs, W1, b1, W2, b2)

In [112]:
print(embedding)

[[1.   3.   3.   5.  ]
 [2.84 3.99 4.   6.  ]]


In [113]:
reb=random_encoder_block(embedding)
print(reb)

[[-22.49968495 -46.3947742   31.6252161  -19.87403458]
 [-22.49968495 -46.3947742   31.6252161  -19.87403458]]


In [114]:
def encoder(x, n=6):
    for _ in range(n):
        x = random_encoder_block(x)
    return x


enc=encoder(embedding)
print(enc)

[[nan nan nan nan]
 [nan nan nan nan]]


<ipython-input-100-85e78fde2c1d>:2: RuntimeWarning: overflow encountered in exp
  return np.exp(x) / np.sum(np.exp(x), axis=1, keepdims=True)
<ipython-input-100-85e78fde2c1d>:2: RuntimeWarning: invalid value encountered in divide
  return np.exp(x) / np.sum(np.exp(x), axis=1, keepdims=True)


In [115]:
mean_embedding_Z=(embedding + Z).mean(axis=-1, keepdims=True)
print(mean_embedding_Z)

[[-4.58837567]
 [-3.59559107]]


In [116]:
std_embedding_Z=(embedding + Z).std(axis=-1, keepdims=True)
print(std_embedding_Z)

[[ 9.92061529]
 [10.50653019]]


In [117]:
def layer_norm(x, epsilon=1e-6):
    mean = x.mean(axis=-1, keepdims=True)
    std = x.std(axis=-1, keepdims=True)
    return (x - mean) / (std + epsilon)

def encoder_block(x, WQs, WKs, WVs, W1, b1, W2, b2):
    Z = multi_head_attention(x, WQs, WKs, WVs)
    Z = layer_norm(Z + x)

    output = feed_forward(Z, W1, b1, W2, b2)
    return layer_norm(output + Z)

L_norm=layer_norm(Z + embedding)
print(L_norm)

[[ 1.71887693 -0.56365339 -0.40370747 -0.75151608]
 [ 1.71909039 -0.56050453 -0.40695381 -0.75163205]]


In [118]:
def encoder(x, n=6):
    for _ in range(n):
        x = random_encoder_block(x)
    return x


enc_emb=encoder(embedding)
print(enc_emb)

[[-1.14690571 -0.07281854 -0.37386515  1.59358941]
 [-1.14690572 -0.07281854 -0.37386514  1.5935894 ]]


In [119]:
d_embedding = 4
n_attention_heads = 2

E = np.array([[1, 1, 0, 1]])
WQs = [np.random.randn(d_embedding, d_query) for _ in range(n_attention_heads)]
WKs = [np.random.randn(d_embedding, d_key) for _ in range(n_attention_heads)]
WVs = [np.random.randn(d_embedding, d_value) for _ in range(n_attention_heads)]

Z_self_attention = multi_head_attention(E, WQs, WKs, WVs)
print(Z_self_attention)

[[ 0.22150133  0.32004543 -3.99199819  0.41807913]]


In [120]:
Z_self_attention = layer_norm(Z_self_attention + E)
print(Z_self_attention)

[[ 0.53433689  0.57716056 -1.73125989  0.61976244]]


In [121]:
def encoder_decoder_attention(encoder_output, attention_input, WQ, WK, WV):
    # В следующих трёх строках и состоит основное различие!
    K = encoder_output @ WK    # Обратите внимание, что теперь мы передаём предыдущие выходные данные кодировщика!
    V = encoder_output @ WV    # Обратите внимание, что теперь мы передаём предыдущие выходные данные кодировщика!
    Q = attention_input @ WQ   # То же, что и для самовнимания

    # Остаётся таким же
    scores = Q @ K.T
    scores = scores / np.sqrt(d_key)
    scores = softmax(scores)
    scores = scores @ V
    return scores


def multi_head_encoder_decoder_attention(
    encoder_output, attention_input, WQs, WKs, WVs
):
    # Обратите внимание, что теперь мы передаём предыдущие выходные данные кодировщика!
    attentions = np.concatenate(
        [
            encoder_decoder_attention(
                encoder_output, attention_input, WQ, WK, WV
            )
            for WQ, WK, WV in zip(WQs, WKs, WVs)
        ],
        axis=1,
    )
    W = np.random.randn(n_attention_heads * d_value, d_embedding)
    return attentions @ W


WQs = [np.random.randn(d_embedding, d_query) for _ in range(n_attention_heads)]
WKs = [np.random.randn(d_embedding, d_key) for _ in range(n_attention_heads)]
WVs = [np.random.randn(d_embedding, d_value) for _ in range(n_attention_heads)]

encoder_output = np.array([[-1.5, 1.0, -0.8, 1.5], [1.0, -1.0, -0.5, 1.0]])

Z_encoder_decoder = multi_head_encoder_decoder_attention(
    encoder_output, Z_self_attention, WQs, WKs, WVs
)

print(Z_encoder_decoder)

[[ 2.72697124 -3.13657083 -4.44877557  2.80038196]]


In [122]:
Z_encoder_decoder = layer_norm(Z_encoder_decoder + Z_self_attention)
print(Z_encoder_decoder)

[[ 0.9294116  -0.50335337 -1.39456724  0.96850901]]


In [123]:
W1 = np.random.randn(4, 8)
W2 = np.random.randn(8, 4)
b1 = np.random.randn(8)
b2 = np.random.randn(4)

output = layer_norm(feed_forward(Z_encoder_decoder, W1, b1, W2, b2) + Z_encoder_decoder)
print(output)

[[-0.27712579  0.47602231 -1.45532843  1.2564319 ]]


In [124]:
d_embedding = 4
d_key = d_value = d_query = 3
d_feed_forward = 8
n_attention_heads = 2
encoder_output = np.array([[-1.5, 1.0, -0.8, 1.5], [1.0, -1.0, -0.5, 1.0]])

def decoder_block(
    x,
    encoder_output,
    WQs_self_attention, WKs_self_attention, WVs_self_attention,
    WQs_ed_attention, WKs_ed_attention, WVs_ed_attention,
    W1, b1, W2, b2,
):
    # То же, что и раньше
    Z = multi_head_attention(
        x, WQs_self_attention, WKs_self_attention, WVs_self_attention
    )
    Z = layer_norm(Z + x)

    # Основное различие заключается в следующих трёх строках!
    Z_encoder_decoder = multi_head_encoder_decoder_attention(
        encoder_output, Z, WQs_ed_attention, WKs_ed_attention, WVs_ed_attention
    )
    Z_encoder_decoder = layer_norm(Z_encoder_decoder + Z)

    # То же, что и раньше
    output = feed_forward(Z_encoder_decoder, W1, b1, W2, b2)
    return layer_norm(output + Z_encoder_decoder)

def random_decoder_block(x, encoder_output):
    # Просто несколько произвольных инициализаций
    WQs_self_attention = [
        np.random.randn(d_embedding, d_query) for _ in range(n_attention_heads)
    ]
    WKs_self_attention = [
        np.random.randn(d_embedding, d_key) for _ in range(n_attention_heads)
    ]
    WVs_self_attention = [
        np.random.randn(d_embedding, d_value) for _ in range(n_attention_heads)
    ]

    WQs_ed_attention = [
        np.random.randn(d_embedding, d_query) for _ in range(n_attention_heads)
    ]
    WKs_ed_attention = [
        np.random.randn(d_embedding, d_key) for _ in range(n_attention_heads)
    ]
    WVs_ed_attention = [
        np.random.randn(d_embedding, d_value) for _ in range(n_attention_heads)
    ]

    W1 = np.random.randn(d_embedding, d_feed_forward)
    b1 = np.random.randn(d_feed_forward)
    W2 = np.random.randn(d_feed_forward, d_embedding)
    b2 = np.random.randn(d_embedding)


    return decoder_block(
        x, encoder_output,
        WQs_self_attention, WKs_self_attention, WVs_self_attention,
        WQs_ed_attention, WKs_ed_attention, WVs_ed_attention,
        W1, b1, W2, b2,
    )
def decoder(x, decoder_embedding, n=6):
    for _ in range(n):
        x = random_decoder_block(x, decoder_embedding)
    return x


dec_enc_out=decoder(E, encoder_output)
print(dec_enc_out)

[[-0.87871785  1.67300064 -0.63534245 -0.15894034]]


In [125]:
def linear(x, W, b):
    return np.dot(x, W) + b

x = linear([1, 0, 1, 0], np.random.randn(4, 10), np.random.randn(10))
print(x)

[-0.25100542 -1.31979351  1.30854114 -2.98388191  1.71615877  1.2947306
 -1.85872236 -1.10394769 -2.19843987 -2.7801584 ]


In [131]:
def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x, keepdims=True)

print(softmax(x))

[0.13673568 0.54152865 0.01384858 0.01070712 0.05474137 0.00209842
 0.12425241 0.06915061 0.04144783 0.00548934]


In [132]:
vocabulary = [
    "hello",
    "mundo",
    "world",
    "how",
    "?",
    "EOS",
    "SOS",
    "a",
    "hola",
    "c",
]
embedding_reps = np.random.randn(10, 4)
vocabulary_embeddings = {
    word: embedding_reps[i] for i, word in enumerate(vocabulary)
}
print(vocabulary_embeddings)

{'hello': array([-0.35165666,  1.65043144,  0.53797996, -0.42548313]), 'mundo': array([ 1.09150189,  0.96717746, -1.31796533,  1.38434922]), 'world': array([0.94496363, 1.03021505, 0.77656003, 0.06628513]), 'how': array([-1.77186851,  0.40955654, -1.27333805, -0.15955161]), '?': array([ 0.79337803, -1.3616285 ,  0.20850618, -0.83816508]), 'EOS': array([-0.23736802, -0.30935027, -0.51520345,  0.52854977]), 'SOS': array([ 1.232424  , -0.59783195,  0.00913838,  0.61834051]), 'a': array([1.33523653, 0.00164602, 1.00973062, 0.92236917]), 'hola': array([ 0.07742248, -1.74372511,  0.68177239, -2.40341855]), 'c': array([1.34421134, 0.494023  , 1.06078546, 0.43702237])}


In [133]:
def generate(input_sequence, max_iters=3):
    # Сначала мы кодируем входные данные в эмбеддинги
    # Для простоты мы пропустим этап позиционного кодирования
    embedded_inputs = [
        vocabulary_embeddings[token] for token in input_sequence
    ]
    print("Embedding representation (encoder input)", embedded_inputs)

    # Затем генерируем описание эмбеддинга
    encoder_output = encoder(embedded_inputs)
    print("Embedding generated by encoder (encoder output)", encoder_output)

    # Инициализируем выходные данные декодера эмбеддингом начального токена
    sequence_embeddings = [vocabulary_embeddings["SOS"]]
    output = "SOS"

    # Случайные матрицы для линейного слоя
    W_linear = np.random.randn(d_embedding, len(vocabulary))
    b_linear = np.random.randn(len(vocabulary))

    # Мы ограничиваем количество этапов декодинга, чтобы избежать слишком последовательностей без EOS
    for i in range(max_iters):
        # Этап декодера
        decoder_output = decoder(sequence_embeddings, encoder_output)

        # Используем для предсказания только последние выходные данные
        logits = linear(decoder_output[-1], W_linear, b_linear)
        # Обёртываем логиты в список, потому что softmax нужны пакеты/2D-массив
        probs = softmax([logits])

        # Получаем наиболее вероятный следующий токен
        next_token = vocabulary[np.argmax(probs)]
        sequence_embeddings.append(vocabulary_embeddings[next_token])
        output += " " + next_token

        print(
            "Iteration", i,
            "next token", next_token,
            "with probability of", np.max(probs),
        )

        # Если следующий токен последний, то возвращаем последовательность
        if next_token == "EOS":
            return output

    return output, sequence_embeddings

In [135]:
print(generate(["hello", "world"]))

Embedding representation (encoder input) [array([-0.35165666,  1.65043144,  0.53797996, -0.42548313]), array([0.94496363, 1.03021505, 0.77656003, 0.06628513])]
Embedding generated by encoder (encoder output) [[ 1.27123538  0.62012382 -1.27032215 -0.62103704]
 [ 1.24332031  0.639001   -1.31147398 -0.57084733]]
Iteration 0 next token how with probability of 0.6142360961970552
Iteration 1 next token EOS with probability of 0.25584905226910837
SOS how EOS
